owner: dricottone
repo: upptime

sites:
  - name: Blog
    url: https://www.dominic-ricottone.com
  - name: Wiki
    url: https://wiki.dominic-ricottone.com
  - name: Code Repo
    url: https://git.dominic-ricottone.com
  - name: Host AWS2
    url: https://aws2.dominic-ricottone.com
  - name: Host Alpine1
    url: https://alpine1.dominic-ricottone.com
  - name: Host Ubuntu1
    url: https://ubuntu1.dominic-ricottone.com
  - name: Go Module Proxy Endpoint
    url: https://go.dominic-ricottone.com
  - name: VPN Endpoint
    url: https://vpn.dominic-ricottone.com
  - name: FTP Endpoint
    url: https://ftp.dominic-ricottone.com
  - name: Docker Registry Endpoint
    url: https://docker.dominic-ricottone.com

status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Dominic Ricottone - Upptime
  introTitle: "Server Uptime"
  introMessage: Powered by Github
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "0 * * * *"
